# Generated by Django 5.2.1 on 2025-06-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_content_type_document_contenttype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='contentType',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='fileSize',
            new_name='file_size',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='uploadedAt',
            new_name='uploaded_at',
        ),
    ]
