# Generated by Django 5.2.1 on 2025-06-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_contenttype_document_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField()),
                ('embedding', models.TextField()),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
